# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings - Accessible via {{ site.myvariable }}.
title: "Martin Berdini Mateo"
description: "Martin Berdini Mateo personal page and blog"
url: "http://berdinidss.es"

# Build settings
markdown: kramdown
google_analytics: G-L3NT9B370C
timezone: Europe/Berlin


plugins:
  - jemoji
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - qr
